config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/about/author', to: 'static_pages#author'

  get '/my_badges', to: 'users/badges#index'

  resources :badges, only: :index

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges, shallow: true
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validate :quantity
  validates :body, presence: true

  private

  def quantity
    return unless question.answers.size > 4
    errors.add(:Количество, "Нельзя добавить больше 4-х ответов")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :image, :rule, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  validates :name, presence: true

  default_scope { order(name: :asc) }
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  has_many :gists

  belongs_to :test

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :questions
  has_many :test_passages
  has_many :users, through: :test_passages

  belongs_to :category
  belongs_to :admin

  scope :by_level, -> (level) { where(level: level) }
  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  scope :by_category, -> (category) { joins(:category).
    where(categories: { name: category }).order('tests.title DESC') }

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.categories_array(category)
    by_category(category).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_save :set_question

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def current_question_number
    number_of_questions - test_questions.count
  end

  def number_of_questions
    test.questions.count
  end

  def completed?
    current_question.nil?
  end

  def terminate!
    current_question = nil
  end

  def result
    (100 * self.correct_questions / test.questions.count)
  end

  def test_passed?
    result >= 85
  end

  def time_over?
    expire_at < Time.current if test.timer
  end

  def time_left
    (expire_at - Time.current).to_i if test.timer
  end

  private

  def expire_at
    created_at + test.timer if test.timer
  end

  def set_question
    self.current_question = self.current_question.nil? ? first_question : next_question
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count

    correct_answers_count == correct_answers.where(id: answer_ids).count &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

  def first_question
    test.questions.first
  end

  def next_question
    test_questions.first
  end

  def test_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :gists
  has_many :feedbacks
  has_many :user_badges
  has_many :badges, through: :user_badges

  validates :last_name, :first_name, presence: true
  validates :email, uniqueness: true

  def passed_tests_by_level(level)
    tests.by_level(level).where( test_passages: {user_id: id} )
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    is_a?(Admin)
  end

  def passed_by_level(level)
    test_passages.joins(:test).where(tests: { level: level })
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to [:admin, @badge]
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def badge_params
    params.require(:badge).permit(:name, :image, :rule, :parameter)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: %i[show start]

  def index
    @tests = Test.all
  end

  def show
    @test = Test.find(params[:id])
    @questions = @test.questions
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/controllers/users/badges_controller.rb
class Users::BadgesController < ApplicationController
  def index
    @badges = current_user.badges
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def answer_header(answer)
    if answer.new_record?
      "Создайте новый ответ для вопроса #{answer.question.body}"
    else
      "Редактирование ответа на вопрос #{answer.question.body}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 ALERTS  = { alert: 'danger',
             notice: 'primary' }.freeze

  def alert_value(key)
    ALERTS[key.to_sym]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
  def gist_hash(url)
    /(?<=com\/).*/.match(url)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Создайте новый вопрос для теста #{question.test.title}"
    else
      "Редактирование вопроса для теста #{question.test.title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'Test Guru', "https://github.com/#{author}/#{repo}", target: :_blank
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_header(test)
    t('.header', title: test.title)
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= link_to badge.name, admin_badge_path(badge) %></td>
  <td><%= image_tag((badge.image), class: 'img-circle img-height-50') %></td>
  <td><%= badge.rule %></td>
  <td><%= link_to 'Edit', edit_admin_badge_path(badge) %></td>
  <td><%= link_to 'Delete', admin_badge_path(badge), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/badges/_form.html.erb
<div class="form-group">
  <%= form_with model: [:admin, @badge], local: true do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name, id: 'badge_Название', class: 'form-control' %>
  </p>

  <p>
    <%= form.label :image %>
    <%= form.text_field :image, id: 'badge_Изображение', class: 'form-control' %>
  </p>

  <p>
    <%= form.label :rule %>
    <%= form.select(:rule, options_for_select([['Первая попытка', 1],
                                               ['Все категории', 2],
                                               ['Все тесты уровня', 3]],
                    selected: @badge.rule), { promt: true},
                    { class: 'form-control' }) %>
  </p>

  <p>
    <%= form.label :parameter %>
    <%= form.text_field :parameter, id: 'badge_Параметр', class: 'form-control' %>
  </p>

  <%= form.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admin/badges/edit.html.erb
<div class="container">
  <%= render 'shared/errors', resource: @badge %>
  <%= render 'form' %>
  <%= render 'shared/back' %>
</div>

app/views/admin/badges/index.html.erb
<div class="container">
  <h3>Badges</h3>
  <div class="row">
    <%= render 'shared/errors', resource: @badge %>
    <table class="table table-light">
      <thead>
        <tr>
          <th scope="col">Название</th>
          <th scope="col">Изображение</th>
          <th scope="col">Правило</th>
          <th scope="col" colspan="2">Действия</th>
        </tr>
      </thead>
      <tbody>
        <%= render @badges %>
      </tbody>
    </table>
  </div>
  <%= link_to 'Create Badge', new_admin_badge_path,
  class: "btn btn-primary"  %>
  <div class="row">
    <div class="col-12">
      <%= render 'shared/back' %>
    </div>
  </div>
</div>

app/views/admin/badges/new.html.erb
<div class="container">
  <%= render 'shared/errors', resource: @badge %>
  <%= render 'form' %>
  <%= render 'shared/back' %>
</div>

app/views/admin/badges/show.html.erb
<h3>
  <%= @badge.name %>
</h3>

<p>
  <%= image_tag((@badge.image), class: 'img-height-50 img-circle') %>
</p>

<p>
  <%= @badge.rule %>
</p>

<%= link_to 'Edit', edit_admin_badge_path(@badge) %>
<%= render 'shared/back' %>

app/views/badges/_badge.html.erb
<tr>
  <td><%= badge.name %></td>
  <td><%= image_tag((badge.image), class: 'img-circle img-height-50') %></td>
  <td><%= badge.rule %></td>
</tr>

app/views/badges/index.html.erb
<div class="container">
  <h3>Badges</h3>
  <div class="row">
    <%= render 'shared/errors', resource: @badge %>
    <table class="table table-light">
      <thead>
        <tr>
          <th scope="col">Название</th>
          <th scope="col">Изображение</th>
          <th scope="col">Правило</th>
        </tr>
      </thead>
      <tbody>
        <%= render @badges %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col-12">
      <%= render 'shared/back' %>
    </div>
  </div>
</div>