config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/about/author', to: 'static_pages#author'

  get '/my_badges', to: 'users/badges#index'

  resources :badges, only: :index

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges, shallow: true
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validate :quantity
  validates :body, presence: true

  private

  def quantity
    return unless question.answers.size > 4
    errors.add(:Количество, "Нельзя добавить больше 4-х ответов")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :image, :rule, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests

  validates :name, presence: true

  default_scope { order(name: :asc) }
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  has_many :gists

  belongs_to :test

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :questions
  has_many :test_passages
  has_many :users, through: :test_passages

  belongs_to :category
  belongs_to :admin

  scope :by_level, -> (level) { where(level: level) }
  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  scope :by_category, -> (category) { joins(:category).
    where(categories: { name: category }).order('tests.title DESC') }

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def self.categories_array(category)
    by_category(category).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_save :set_question

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def current_question_number
    number_of_questions - test_questions.count
  end

  def number_of_questions
    test.questions.count
  end

  def completed?
    current_question.nil?
  end

  def terminate!
    current_question = nil
  end

  def result
    (100 * self.correct_questions / test.questions.count)
  end

  def test_passed?
    result >= 85
  end

  def time_over?
    expire_at < Time.current if test.timer
  end

  def time_left
    (expire_at - Time.current).to_i if test.timer
  end

  private

  def expire_at
    created_at + test.timer if test.timer
  end

  def set_question
    self.current_question = self.current_question.nil? ? first_question : next_question
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count

    correct_answers_count == correct_answers.where(id: answer_ids).count &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

  def first_question
    test.questions.first
  end

  def next_question
    test_questions.first
  end

  def test_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :gists
  has_many :feedbacks
  has_many :user_badges
  has_many :badges, through: :user_badges

  validates :last_name, :first_name, presence: true
  validates :email, uniqueness: true

  def passed_tests_by_level(level)
    tests.by_level(level).where( test_passages: {user_id: id} )
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    is_a?(Admin)
  end

  def passed_by_level(level)
    test_passages.joins(:test).where(tests: { level: level })
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/helpers/answers_helper.rb
module AnswersHelper
  def answer_header(answer)
    if answer.new_record?
      "Создайте новый ответ для вопроса #{answer.question.body}"
    else
      "Редактирование ответа на вопрос #{answer.question.body}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 ALERTS  = { alert: 'danger',
             notice: 'primary' }.freeze

  def alert_value(key)
    ALERTS[key.to_sym]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/gists_helper.rb
module GistsHelper
  def gist_hash(url)
    /(?<=com\/).*/.match(url)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Создайте новый вопрос для теста #{question.test.title}"
    else
      "Редактирование вопроса для теста #{question.test.title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to 'Test Guru', "https://github.com/#{author}/#{repo}", target: :_blank
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_header(test)
    t('.header', title: test.title)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="main">
      <%= yield %>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <%= render 'shared/flash' %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_back.html.erb
<%= link_to 'Назад', 'javascript:history.go(-1)' %>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors row', data: { resource_id: resource.id } do %>
    <h2 class="col-12"><%= pluralize(resource.errors.count, 'error') %> detected:</h2>
      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "alert alert-#{alert_value(key)}", role: 'alert' %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer font-small">
  <div class="container">
    <div class="row pt-5 mb-3 text-center justify-content-center">
    <div class="col-md-3">
        <h6 class="title font-weight-bold"><%= link_to 'О проекте', about_path %></h6>
      </div>
      <div class="col-md-3">
        <h6 class="title font-weight-bold">
          <%=  github_url('JakuninOleg', 'TestGuru')%>
        </h6>
      </div>
      <div class="col-md-3">
        <h6 class="title font-weight-bold"><%= link_to 'Автор', about_author_path %></h6>
      </div>
      <div class="col-md-3">
        <h6 class="title font-weight-bold"><%= link_to 'Обратная связь', new_feedback_path %></h6>
      </div>
    </div>
  </div>
  <div class="footer-copyright py-3 text-center">
    <div class="container-fluid">
      <%= link_to 'Учебный проект в онлайн-школе Thinknetica',
      'https://thinknetica.com', target: :_blank %><br />
      <h6>©<%= current_year %></h6>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-xxl navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <div class="mr-2">
    <% if current_user&.admin? %>
      Welcome Admin <%= current_user.last_name %> <%= current_user.first_name %>
      <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
    <% elsif user_signed_in? %>
      Welcome <%= current_user.email %>
      <%= link_to 'Выйти', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Логин', new_user_session_path %>
      <%= link_to 'Регистрация', new_user_registration_path %>
    <% end %>
  </div>
</nav>